<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {

    $projectsList = [
        "Accounting-software (2)",
        "Appartment / Apartment (2)",
        "Bedesk (1)",
        "Blood-Bank-Management-System / Blood-Bank (4)",
        "cms / cms1 / cms4 (4)",
        "crmone / CRM / CRM_PRO (3)",
        "dating (2)",
        "Deepsound (1)",
        "Doctorin / doctor-management / Doctor-Appointment-System (4)",
        "ecommercemultivendor / Ecommerce / ecomsingle / Ecommerce2 (6)",
        "Edufirm (1)",
        "email / Mailer (2)",
        "erp / ERP (3)",
        "filesharing (2)",
        "Foodordering / Food-Ordering-System / Online-Food-Order (4)",
        "Forumlab (1)",
        "hosting (2)",
        "hrms / Human-Resource-Management-System / HumanResourceManagementSystem (5)",
        "industry (1)",
        "institute (2)",
        "inventory / Stock-Management / Inventory_And_Monitoring_System (7)",
        "itest (1)",
        "Jobboard / jobportal / Jobportal (4)",
        "library / Library-Management-System (4)",
        "loan / Loan-Management-System (4)",
        "marketplace (2)",
        "matrimony / Matrimonial (2)",
        "mlm (3)",
        "Multihotelbooking (1)",
        "multiwebsite (2)",
        "Nft / Nftzai (2)",
        "pharmacy / Pharmacy-Management-System (4)",
        "Portfolio (1)",
        "projectmanagement / Project-Management-System / Ult-Projectms (4)",
        "Realstatepro / Real-Estate (2)",
        "Repair (1)",
        "Reserve (1)",
        "restaurant / Restaurant-Management / Online-Restarant-Order / Smart-Restaurant (7)",
        "Restrobooking (1)",
        "Restrosaas (1)",
        "resume (2)",
        "Retailstore (1)",
        "saloon (3)",
        "schoolone / schoolone1 / School_Fees_System (4)",
        "Shippingmaster (1)",
        "Supportdesk (1)",
        "Ticketsales (1)",
        "travel / Online-Travel-System / New Travel (4)",
        "Assessment-Management-System (1)",
        "Daily-Expense-Manager (1)",
        "Expense-Tracker (1)",
        "Farm-management-System (1)",
        "Gym-Management-System / GYM (3)",
        "Hospital-Information-System / Hospital-Management-System / Hospital (6)",
        "Hotel-Management-System / Hotel (3)",
        "Internship-Management-System (1)",
        "Interview-Management (1)",
        "LMS / Online-Course (2)",
        "Online-exam-system / ONLINE-EXAM-SYSTEM (5)",
        "Online-Job-Portal-System / Online_Job_Portal_System (4)",
        "Online-Library-Management-System (1)",
        "Online-Quiz / Quiz (4)",
        "Online-Voting-System (3)",
        "Patient-Record-Management-System (1)",
        "Point-of-Sale / POS (3)",
        "Record-Management-System (1)",
        "Smart-Parking-Management-System / Smart-parking (2)",
        "Student-Management-System / Student-Record-Management-System (6)",
        "Visitor-Management-System (1)",
        "attendance / Attendance (2)",
        "Bus-Booking / bus-booking-system-PHP (2)",
        "Cable-Management-System (1)",
        "Catering-Management-System (1)",
        "Clothstore-Management-System (1)",
        "Dignostic-Management-System (1)",
        "E-Bank-Management (1)",
        "easypos (1)",
        "Election (1)",
        "Fleet (1)",
        "Invoice (1)",
        "Jewellery-Store-System (1)",
        "Laundry-Management-System / Laundry (2)",
        "Loan-Management-System (2)",
        "Online-Ticket-Reservation-Project (1)",
        "Pharma (2)",
        "Photo-Studio-Management (1)",
        "Tailor (1)",
        "Tenant (1)"
    ];    
    return view('welcome', [
        'projects' => $projectsList,
    ]);
});
